# Generated by Django 3.1.2 on 2020-10-28 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='candidate/'),
        ),
        migrations.AlterField(
            model_name='election',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='election/'),
        ),
    ]
